# Generated by Django 5.0.1 on 2024-04-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_messages',
            name='links',
            field=models.TextField(null=True),
        ),
    ]
